List of Goods
mate-academy/react_list-of-goods-js pull request #201
Opened 2023-08-17 20:17 UTC by DenisGurskiy

https://DenisGurskiy.github.io/react_list-of-goods-js/

2023-08-18 06:37 UTC, volodymyr-soltys97 requested changes
Good job 👍 
Let's improve your code

2023-08-18 06:37 UTC, volodymyr-soltys97 commented on src/App.jsx
> +            { 'is-light': sortBy !== SORT_BY_LENGTH })}
You can create a helper variable for this `sortBy !== SORT_BY_LENGTH` and use them everywhere
```suggestion
            { 'is-light': sortBy !== SORT_BY_LENGTH })}
```

2023-08-18 06:37 UTC, volodymyr-soltys97 commented on src/App.jsx
> +          onClick={() => setReverse(!reverse)}
You can create a helper function for this and use it everywhere

2023-08-19 08:27 UTC, sTorba24 approved these changes

2024-03-11 20:25 UTC, closed without merging