solution
mate-academy/react_list-of-goods-js pull request #245
Opened 2023-08-27 12:36 UTC by Valentyn-Bilyk

[DEMO LINK](https://Valentyn-Bilyk.github.io/react_list-of-goods-js/)

2023-08-27 14:57 UTC, edgergard approved these changes
🔥🔥🔥

2023-08-28 14:33 UTC, polosanya requested changes
Nice! Let's improve your code a bit)

2023-08-28 14:33 UTC, polosanya commented on src/App.jsx
> +const GOOD_LEGTH = 'length';
```suggestion
const GOOD_LENGTH = 'length';
```

2023-08-28 14:33 UTC, polosanya commented on src/App.jsx
> +          return 0;
In this case, you will call the sort method even if it's not needed. Consider moving switch...case outside of the sort callback

2023-08-28 14:33 UTC, polosanya commented on src/App.jsx
> +  const [isReverse, setIsReverse] = useState(false);
```suggestion
  const [isReversed, setIsReversed] = useState(false);
```

2023-08-28 14:33 UTC, polosanya commented on src/App.jsx
> +        {(sortField || isReverse) && (
It would be great to create a variable for that condition

2023-08-28 14:33 UTC, polosanya commented on src/App.jsx
> +              setIsReverse(false);
Let's create a separate function to handle this click

2023-08-31 08:49 UTC, Moroz-Dmytro requested changes

2023-08-31 08:49 UTC, Moroz-Dmytro commented on src/App.jsx
> +            'is-light': isReversed !== true,
```suggestion
            'is-light': !isReversed,
```

2023-08-31 08:49 UTC, Moroz-Dmytro commented on src/App.jsx
> +        {(sortField || isReversed) && (
Create variable for this value

2023-08-31 13:11 UTC, roman-mirzoian requested changes
Be careful with the comments, you leave the same comment several times without correction.

2023-08-31 15:07 UTC, BudnikOleksii approved these changes
Good work  🚀

2026-01-24 21:50 UTC, closed without merging