Create sort function
mate-academy/react_list-of-goods-js pull request #254
Opened 2023-08-27 17:00 UTC by rostyslav48

https://rostyslav48.github.io/react_list-of-goods-js/

2023-08-28 15:10 UTC, vserhiichuk approved these changes
It looks good!

2023-08-29 09:32 UTC, polosanya requested changes
Good job! I'm approving it, but please pay attention to the comments

2023-08-29 09:32 UTC, polosanya commented on src/App.jsx
> +      </ul>
```suggestion
      <ul>
        {sortedGoods.map(({ product, id }) => (
          <li data-cy="Good" key={id}>
            {product}
          </li>
        ))}
      </ul>
```

2023-08-29 09:32 UTC, polosanya commented on src/App.jsx
> +        return 0;
I think there is no need to call the sort method at all if it's the default case

2023-08-29 09:32 UTC, polosanya approved these changes

2025-08-31 20:10 UTC, closed without merging