stage-1
mate-academy/react_list-of-goods-js pull request #344
Opened 2023-10-09 18:23 UTC by no4kar

[DEMO LINK](https://no4kar.github.io/react_list-of-goods-js/)

2023-10-09 18:29 UTC, Viktor-Kost requested changes
GJ!
Some moments can be improved

2023-10-09 18:29 UTC, Viktor-Kost commented on src/App.jsx
> +  const [isSortRevers, setIsSortRevers] = useState(false);
```suggestion
  const [isSortReversed, setIsSortReversed] = useState(false);
```

2023-10-09 18:29 UTC, Viktor-Kost commented on src/App.jsx
> +        {(sortBy !== '' || isSortRevers === true)
```suggestion
        {(sortBy || isSortReversed)
```

2023-10-09 18:29 UTC, Viktor-Kost commented on src/App.jsx
> +  };
```suggestion
  const handleSortReversed = () => {
    setIsSortReversed(prev => !prev);
  };
```

2023-10-09 18:29 UTC, Viktor-Kost commented on src/App.jsx
> +  const handlerSortReset = () => {
function names should start with a verb
```suggestion
  const handleSortReset = () => {
```

2023-10-10 05:59 UTC, volodymyr-soltys97 approved these changes
Great work 🔥

2025-09-20 15:49 UTC, closed without merging