solution
mate-academy/react_list-of-goods-js pull request #523
Opened 2023-12-20 15:34 UTC by maksym-kostetskyi

https://maksym-kostetskyi.github.io/react_list-of-goods-js/

2023-12-20 16:12 UTC, Viktor-Kost requested changes

2023-12-20 16:12 UTC, Viktor-Kost commented on src/App.jsx
> +  const [reversed, setReversed] = useState(false);
```suggestion
  const [isReversed, setIsReversed] = useState(false);
```
https://dev.to/michi/tips-on-naming-boolean-variables-cleaner-code-35ig

2023-12-20 16:12 UTC, Viktor-Kost commented on src/App.jsx
> +  const [lengthClicked, setLengthClicked] = useState(false);
you should use only one state (sortField) for all of these cases

2023-12-20 16:12 UTC, Viktor-Kost commented on src/App.jsx
> +  function clickName() {
depends on what you click you will just set a correct sortField. 
So you don't need to have all of these handlers

2023-12-20 16:12 UTC, Viktor-Kost commented on src/App.jsx
> +  function clickReset() {
you need just to reset `isReversed` and `sortField`

2023-12-22 11:24 UTC, VitaliyBondarenko1982 requested changes
Almost done.
Suggest some refactoring.

2023-12-22 11:24 UTC, VitaliyBondarenko1982 commented on src/App.jsx
> +          )}
```suggestion
            <button
              type="button"
              id="reverse"
              className={cn("button is-warning", { isLight: !isReversed })}
              onClick={() => setIsReversed(prevIsReversed => !prevIsReversed)}
            >
              Reverse
            </button>
```
 use classnames library for dynamic set classNames. no need repeat jsx for it.
 same for other buttons
 
better change isReversed from prev state

2023-12-22 11:24 UTC, VitaliyBondarenko1982 commented on src/App.jsx
> +  }
```suggestion
    preparedGoods.sort((good1, good2) => {
      switch (sortField) {
        case SORT_FIELD_NAME:
          return good2.localeCompare(good1);

        case SORT_FIELD_LENGTH:
          return good2.length - good1.length;

        default:
          return 0;
      }
    });

  if (isReversed) {
    return preparedGoods.reverse();
  }
```
just reverse if it needs after sorting.

2023-12-22 12:28 UTC, VitaliyBondarenko1982 approved these changes
Well done

2024-12-10 17:59 UTC, closed without merging