Solution
mate-academy/react_list-of-goods-js pull request #569
Opened 2024-01-08 06:54 UTC by YevhenOstrovskiy

2024-01-08 23:58 UTC, EdenParadise requested changes
Good job, but need to implement some changes. Keep it up!

2024-01-08 23:58 UTC, EdenParadise commented on src/App.jsx
> +      setGoods([...goods].sort((a, b) => b.localeCompare(a)));
create const for 
`[...goods]` 
and use it afterwards in your code

2024-01-08 23:58 UTC, EdenParadise commented on src/App.jsx
> +    setGoods([...goods].sort((a, b) => a.localeCompare(b)));
Same here
create const
`const preparedGoods = [...goods];`

2024-01-08 23:58 UTC, EdenParadise commented on src/App.jsx
> +      setGoods([...goods].sort((a, b) => b.length - a.length));
Same here
create const
`const preparedGoods = [...goods];`

2024-01-22 14:22 UTC, DanilWeda approved these changes
Good job! 
Approved.
I left comments about code splitting, please fix it! 
Thanks.

2024-01-22 14:22 UTC, DanilWeda commented on src/App.jsx
> +}
you can move it outside component file

2024-01-22 14:22 UTC, DanilWeda commented on src/App.jsx
> +        {(sortGoods.length > 0 || isReversed) && (
```suggestion
        {(sortGoods.length  || isReversed) && (
```
as alternative*

2024-01-22 14:22 UTC, DanilWeda commented on src/App.jsx
> +          }}
you can write a handler for it ( not critical )

2024-01-22 14:22 UTC, DanilWeda commented on src/App.jsx
> +          }}
you can write a handler for it ( not critical )

2024-09-01 16:46 UTC, closed without merging