solution
mate-academy/react_list-of-goods-js pull request #573
Opened 2024-01-08 19:26 UTC by BodyaKutsyk

[DEMO LINK](https://BodyaKutsyk.github.io/react_list-of-goods-js/)

2024-01-08 19:44 UTC, etojeDenys requested changes

2024-01-08 19:44 UTC, etojeDenys commented on src/App.jsx
> +            }
why do you need it here, if you already have reverse logic in the getPreparedGoods

2024-01-08 20:01 UTC, SanyaBratashchuk requested changes

2024-01-08 20:01 UTC, SanyaBratashchuk commented on src/App.jsx
> +            }
```suggestion
```

2024-01-08 20:01 UTC, SanyaBratashchuk commented on src/App.jsx
> +            setReverse(!reverse);
```suggestion
            setReverse(prev => !prev);
```

2024-01-08 20:01 UTC, SanyaBratashchuk commented on src/App.jsx
> +  const [reverse, setReverse] = useState(false);
```suggestion
  const [isReversed, setIsReversed] = useState(false);
```

2024-01-09 07:13 UTC, volodymyr-soltys97 requested changes
.

2024-01-09 07:13 UTC, volodymyr-soltys97 commented on src/App.jsx
> +      break;
```suggestion
    case SORT_FIELD_LENGTH:
      preparedGoods = preparedGoods
        .sort((elem1, elem2) => elem1.length - elem2.length);
      break;
      
    case SORT_FIELD_ALPHA:
      preparedGoods = preparedGoods
        .sort((elem1, elem2) => elem1.localeCompare(elem2));
      break;
```

2024-01-09 07:13 UTC, volodymyr-soltys97 commented on src/App.jsx
> +            }
Still not fixed from the previous review
```suggestion
```

2024-01-09 09:15 UTC, lerastarynets approved these changes
lgtm 🚀

2026-07-11 19:06 UTC, closed without merging