Solution
mate-academy/react_list-of-goods-js pull request #7
Opened 2023-06-27 15:28 UTC by HannaVasylieva

https://HannaVasylieva.github.io/react_list-of-goods-js/

2023-06-27 16:30 UTC, Viktor-Kost requested changes

2023-06-27 16:30 UTC, Viktor-Kost commented on src/App.jsx
> +  if (toDo) {
no needs to add this condition
```suggestion
```

2023-06-27 16:30 UTC, Viktor-Kost commented on src/App.jsx
> +            : good1.localeCompare(good2);
```suggestion
  return good1.length - good2.length;
```

2023-06-27 16:30 UTC, Viktor-Kost commented on src/App.jsx
> +            : good1.localeCompare(good2);
```suggestion
return good1.localeCompare(good2);
```

2023-06-27 16:30 UTC, Viktor-Kost commented on src/App.jsx
> +            }}
move handler to an own function

2023-06-28 06:32 UTC, etojeDenys requested changes
change it everywhere

2023-06-28 06:32 UTC, etojeDenys commented on src/App.jsx
> +            'is-info',
```suggestion
            'button is-info',
```

2023-06-28 08:41 UTC, mykhalenych approved these changes

2023-11-20 06:36 UTC, closed without merging